name: Pull Request Testing

on:
  pull_request:

jobs:
  ios_build:
    name: Build for iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Inject staging configuration
      run: ./scripts/inject-staging.sh ${{ secrets.MS_APP_CENTER_SECRET_STAGING}} ${{ secrets.MS_APP_CENTER_URL_SCHEME_STAGING }} ${{ secrets.STAGING_ROOT_URL }} ${{ secrets.HTTP_SCHEME }} ${{ secrets.STAGING_APP_NAME }} ${{ secrets.STAGING_APP_BUNDLE_ID }} ${{ secrets.FOURSQUARE_API_KEY }} ${{ secrets.PARSE_APPLICATION_ID }}

    - name: Decrypt secrets
      run: ./scripts/decrypt-secrets.sh ${{ secrets.IOS_KEYS_SECRET }}

    - name: Clean & Build App
      run: ./scripts/build-app-staging.sh
  
  ios_test:
    runs-on: macos-latest
    name: Test for iOS
    needs: ios_build
    steps:
      - uses: actions/checkout@master

      - name: Inject staging configuration
        run: ./scripts/inject-staging.sh ${{ secrets.MS_APP_CENTER_SECRET_STAGING}} ${{ secrets.MS_APP_CENTER_URL_SCHEME_STAGING }} ${{ secrets.STAGING_ROOT_URL }} ${{ secrets.HTTPS_SCHEME }} ${{ secrets.STAGING_APP_NAME }} ${{ secrets.STAGING_APP_BUNDLE_ID }} ${{ secrets.FOURSQUARE_API_KEY }} ${{ secrets.PARSE_APPLICATION_ID }}

      - name: Decrypt secrets
        run: ./scripts/decrypt-secrets.sh ${{ secrets.IOS_KEYS_SECRET }}      

      - name: Run iOS sim tests
        run: ./scripts/test-app-staging.sh
